/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: lizards.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "lizards.pb-c.h"
void   remote_char__init
                     (RemoteChar         *message)
{
  static const RemoteChar init_value = REMOTE_CHAR__INIT;
  *message = init_value;
}
size_t remote_char__get_packed_size
                     (const RemoteChar *message)
{
  assert(message->base.descriptor == &remote_char__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t remote_char__pack
                     (const RemoteChar *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &remote_char__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t remote_char__pack_to_buffer
                     (const RemoteChar *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &remote_char__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RemoteChar *
       remote_char__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RemoteChar *)
     protobuf_c_message_unpack (&remote_char__descriptor,
                                allocator, len, data);
}
void   remote_char__free_unpacked
                     (RemoteChar *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &remote_char__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ok_message__init
                     (OkMessage         *message)
{
  static const OkMessage init_value = OK_MESSAGE__INIT;
  *message = init_value;
}
size_t ok_message__get_packed_size
                     (const OkMessage *message)
{
  assert(message->base.descriptor == &ok_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ok_message__pack
                     (const OkMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ok_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ok_message__pack_to_buffer
                     (const OkMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ok_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OkMessage *
       ok_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OkMessage *)
     protobuf_c_message_unpack (&ok_message__descriptor,
                                allocator, len, data);
}
void   ok_message__free_unpacked
                     (OkMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ok_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   score_message__init
                     (ScoreMessage         *message)
{
  static const ScoreMessage init_value = SCORE_MESSAGE__INIT;
  *message = init_value;
}
size_t score_message__get_packed_size
                     (const ScoreMessage *message)
{
  assert(message->base.descriptor == &score_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t score_message__pack
                     (const ScoreMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &score_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t score_message__pack_to_buffer
                     (const ScoreMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &score_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScoreMessage *
       score_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScoreMessage *)
     protobuf_c_message_unpack (&score_message__descriptor,
                                allocator, len, data);
}
void   score_message__free_unpacked
                     (ScoreMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &score_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor remote_char__field_descriptors[5] =
{
  {
    "msg_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RemoteChar, msg_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RemoteChar, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ch",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RemoteChar, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nchars",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RemoteChar, nchars),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(RemoteChar, n_direction),
    offsetof(RemoteChar, direction),
    &direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned remote_char__field_indices_by_name[] = {
  2,   /* field[2] = ch */
  4,   /* field[4] = direction */
  1,   /* field[1] = id */
  0,   /* field[0] = msg_type */
  3,   /* field[3] = nchars */
};
static const ProtobufCIntRange remote_char__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor remote_char__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RemoteChar",
  "RemoteChar",
  "RemoteChar",
  "",
  sizeof(RemoteChar),
  5,
  remote_char__field_descriptors,
  remote_char__field_indices_by_name,
  1,  remote_char__number_ranges,
  (ProtobufCMessageInit) remote_char__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ok_message__field_descriptors[1] =
{
  {
    "msg_ok",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OkMessage, msg_ok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ok_message__field_indices_by_name[] = {
  0,   /* field[0] = msg_ok */
};
static const ProtobufCIntRange ok_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ok_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ok_message",
  "OkMessage",
  "OkMessage",
  "",
  sizeof(OkMessage),
  1,
  ok_message__field_descriptors,
  ok_message__field_indices_by_name,
  1,  ok_message__number_ranges,
  (ProtobufCMessageInit) ok_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor score_message__field_descriptors[1] =
{
  {
    "my_score",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ScoreMessage, my_score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned score_message__field_indices_by_name[] = {
  0,   /* field[0] = my_score */
};
static const ProtobufCIntRange score_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor score_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "score_message",
  "ScoreMessage",
  "ScoreMessage",
  "",
  sizeof(ScoreMessage),
  1,
  score_message__field_descriptors,
  score_message__field_indices_by_name,
  1,  score_message__number_ranges,
  (ProtobufCMessageInit) score_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue direction__enum_values_by_number[5] =
{
  { "UP", "DIRECTION__UP", 0 },
  { "DOWN", "DIRECTION__DOWN", 1 },
  { "LEFT", "DIRECTION__LEFT", 2 },
  { "RIGHT", "DIRECTION__RIGHT", 3 },
  { "NONE", "DIRECTION__NONE", 4 },
};
static const ProtobufCIntRange direction__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex direction__enum_values_by_name[5] =
{
  { "DOWN", 1 },
  { "LEFT", 2 },
  { "NONE", 4 },
  { "RIGHT", 3 },
  { "UP", 0 },
};
const ProtobufCEnumDescriptor direction__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Direction",
  "Direction",
  "Direction",
  "",
  5,
  direction__enum_values_by_number,
  5,
  direction__enum_values_by_name,
  1,
  direction__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
